# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0fsatnux.grpc.api\"\x1e\n\nApiRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"\x1b\n\x0b\x41piResponse\x12\x0c\n\x04resp\x18\x01 \x01(\t2O\n\x03\x41pi\x12H\n\x0b\x41piEndpoint\x12\x1b.satnux.grpc.api.ApiRequest\x1a\x1c.satnux.grpc.api.ApiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIREQUEST']._serialized_start=30
  _globals['_APIREQUEST']._serialized_end=60
  _globals['_APIRESPONSE']._serialized_start=62
  _globals['_APIRESPONSE']._serialized_end=89
  _globals['_API']._serialized_start=91
  _globals['_API']._serialized_end=170
# @@protoc_insertion_point(module_scope)
